---
title: "ReproRes Poll Class 04"
format: dashboard
---


```{r setup, include=FALSE}
library(kableExtra)
library(tidyverse)
library(googlesheets4)
options(gargle_oauth_email = "debruine@gmail.com")
library(ggthemes)
library(see)
library(ggwordcloud) # for word clouds
library(tidytext) # for manipulating text for word clouds
```

```{r, eval = TRUE}
theme_set(theme_fivethirtyeight(base_size = 24))
scale_fill <- scale_fill_brewer(palette = "Spectral", drop=FALSE)
scale_colour <- scale_colour_brewer(palette = "Spectral", drop=FALSE)
```

```{r}
# read data
url <- "1o3dPW6yKUVE7pdnPKtfusW5reMtnQi7yQi5La2uafe4"
data <- read_sheet(url, sheet = "Week4")


engage <- c(book = "Read the book", 
            exercise = "Did the formative exercise",
            none = "I didn't get a chance this week")

n <- nrow(data)
```

`r n` Participants

Row {data-height=400}
-----------------------------------------------------------------------

### How did you engage with Chapter 4?

```{r}
subdat <- select(data, x = 2) %>%
  separate_rows(x, sep = ", ") %>%
  mutate(x = factor(x, rev(engage), rev(names(engage))))

ggplot(subdat, aes(x = x, fill = x)) +
  geom_bar(show.legend = FALSE, colour = "black") +
  scale_x_discrete(name = "",  drop=FALSE) +
  scale_y_continuous(name = "", breaks = 0:11*5) +
  scale_fill +
  coord_flip(ylim = c(0, n)) 
```

### What have you completed for the mid-term assessment?

```{r}
midterm <- c(download = "Downloaded my data",
             project = "Created a project",
             qmd = "Created the quarto file",
             YAML = "Edited the YAML header",
             biblio = "Set up the bibliography",
             headers = "Added the header structure and text",
             loaded = "Loaded the data",
             plot1 = "Plot 1",
             plot2 = "Plot 2",
             plot3 = "Plot 3",
             table1 = "Table 1",
             table2 = "Table 2")

subdat <- select(data, x = 5) %>%
  separate_rows(x, sep = ", ") %>%
  mutate(x = factor(x, rev(midterm), rev(names(midterm))))

ggplot(subdat, aes(x = x, fill = x)) +
  geom_bar(show.legend = FALSE, colour = "black") +
  scale_x_discrete(name = "",  drop=FALSE) +
  scale_y_continuous(name = "", breaks = 0:11*5) +
  scale_fill +
  coord_flip(ylim = c(0, n)) 
```


Row {data-height=400}
-----------------------------------------------------------------------

### List concepts you learned in Chapter 4 that you feel confident about.

```{r}
#| title: Confident
omitted <- c(stop_words$word, "im", 0:9)

words <- select(data, word = 3) %>%
  filter(!is.na(word)) %>%
  separate_longer_delim(word, stringr::regex("\\s*(,|;)\\s*")) |>
  count(word) %>%
  filter(word != "", n > 0, !word %in% omitted) %>%
  slice_max(order_by = n, n = 25, with_ties = FALSE)

ggplot(words, aes(label = word, colour = word, size = n)) +
  geom_text_wordcloud_area() +
  scale_size_area(max_size = 14) +
  theme_minimal(base_size = 10) +
  scale_color_see_d(palette = "ice") 
```




### List concepts you learned in Chapter 4 that you feel less confident about and would like reviewed in class today.

```{r}
#| title: Less Confident
omitted <- c(stop_words$word, "im", 0:9)

words <- select(data, word = 4) %>%
  filter(!is.na(word)) %>%
  separate_longer_delim(word, stringr::regex("\\s*(,|;)\\s*")) |>
  count(word) %>%
  filter(word != "", n > 0, !word %in% omitted) %>%
  slice_max(order_by = n, n = 25, with_ties = FALSE)

ggplot(words, aes(label = word, colour = word, size = n)) +
  geom_text_wordcloud_area() +
  scale_size_area(max_size = 20) +
  theme_minimal(base_size = 14) +
  scale_color_see_d(palette = "ice") 
```

Row 
-----------------------------------------------------------------------

### Confident 

```{r}
#| title: Confident
select(data, word = 3) %>%
  filter(!is.na(word)) %>%
  separate_longer_delim(word, stringr::regex("\\s*(,|;)\\s*")) |>
  filter(word != "") %>%
  kable(row.names = FALSE, col.names = "") %>%
  kable_classic(lightable_options = "striped")
```


### Not Confident 

```{r}
#| title: Less Confident
select(data, word = 4) %>%
  filter(!is.na(word)) %>%
  separate_longer_delim(word, stringr::regex("\\s*(,|;)\\s*")) |>
  filter(word != "") %>%
  kable(row.names = FALSE, col.names = "") %>%
  kable_classic(lightable_options = "striped")
```

