---
title: ReproRes 2024
format:
  html:
    toc: true
    toc-depth: 3
    toc-expand: 3
    toc-title: Page Contents
---

## Class 01 (2024-09-27)


### Pre-Class 

- [ ] Make sure you can access [Moodle](https://moodle.gla.ac.uk/course/view.php?id=44432)
- [ ] Bookmark the [Teams channel for PSYCH5077](https://sway.cloud.microsoft/ZRGtRvWTGltD5q3P) and Introduce yourself
- [ ] Read the [overview](https://psyteachr.github.io/reprores-v4/) and [Chapter 1](https://psyteachr.github.io/reprores-v4/01-intro.html) of the textbook
- [ ] Install R and RStudio on your computer
    - post on Teams if you run into problems
    - if you don't have a personal computer, you can use university computers; log on and familiarise yourself with R and RStudio
    - If you have a chromebook or tablet, you can't install R, but can use the RStudio server (log in with your GUID)
- [ ] Download and render the [test file](resources/reprores_test.qmd) to check that your setup is accurate
- [ ] Add these assessment dates to your diary
    - 2024-10-09 (10%) A project with a qmd file showing basic reproducible report skills (chapters 1-2)
    - 2024-10-23 (20%) A project demonstrating data visualisation and summary skills (chapters 3-4)
    - 2024-11-13 (30%) A project demonstrating data wrangling skills (chapters 5-7)
    - 2024-12-11 (40%) A project showing power simulation (chapters 8-10)
- [ ] Fill out the [pre-class poll](https://forms.gle/iPwNuTg5aooVjSvN7)

### In-Class

- [Poll 1](polls/poll-01.html)
- Open the [class book](https://psyteachr.github.io/reprores-v4/)
- Open RStudio 
- Start at 13:05
- [Why Code?](https://debruine.github.io/why-code/) presentation
- Discuss the [class syllabus](https://moodle.gla.ac.uk/course/view.php?id=44432)
- Break
- [Chapter 1](https://psyteachr.github.io/reprores-v4/01-intro.html) live code

### Class Notes

- log into desktops with campus\12345678X and GUID password

## Class 02 (2024-10-04)

### Pre-Class

- [ ] Read [Chapter 2: Reports](https://psyteachr.github.io/reprores-v4/02-reports.html)
- [ ] Complete the [exercises](https://psyteachr.github.io/reprores-v4/02-reports.html#sec-exercises-reports) for chapter 2
- [ ] Look at [assessment 1](https://psyteachr.github.io/reprores-v4/assessment-1.html)
- [ ] Fill out the [pre-class poll](https://forms.gle/6JkELpVZcK3j5W7P6)

### In-Class

- [Poll 2](polls/poll-02.html)
- Open the [class book](https://psyteachr.github.io/reprores-v4/)
- Open RStudio 
- Start at 13:05
- [Chapter 2](https://psyteachr.github.io/reprores-v4/02-reports.html) live code
- Break
- [Assessment 1](https://psyteachr.github.io/reprores-v4/assessment-1.html) questions

## Class 03 (2024-10-11)

### Pre-Class

- Submit [assessment 1](https://psyteachr.github.io/reprores-v4/assessment-1.html) by noon on Wednesday
- Read [Chapter 3: DataViz](https://psyteachr.github.io/reprores-v4/03-viz.html)
- Complete the [exercises](https://psyteachr.github.io/reprores-v4/03-viz.html#exercises) for chapter 3
- Fill out the [pre-class poll](https://forms.gle/g6YoyMgtLQBqgyH89)

### In-Class

- [Poll 3](polls/poll-03.html)
- Open the [class book](https://psyteachr.github.io/reprores-v4/)
- Open RStudio 
- Start at 13:05
- Paired coding exercise
- Break
- [Chapter 3](https://psyteachr.github.io/reprores-v4/03-viz.html) overview
- [Assessment 2](https://psyteachr.github.io/reprores-v4/assessment-2.html) overview


## Class 04 (2024-10-18)

### Pre-Class

- Read [Chapter 4: Summaries](https://psyteachr.github.io/reprores-v4/04-summary.html)
- Complete the [exercises](https://psyteachr.github.io/reprores-v4/04-summary.html#exercises)
- Fill out the [pre-class poll](https://forms.gle/ZWiUH44aZZahGvwZ9)

### In-Class

- [Poll 4](polls/poll-04.html)
- Open the [class book](https://psyteachr.github.io/reprores-v4/)
- Open RStudio 
- Download [psychological therapies referral data](https://www.opendata.nhs.scot/dataset/psychological-therapies-waiting-times/resource/cfc4b998-c3d6-418f-91e6-a17806de94e0)
- Start at 13:05
- Paired programming
    1. Set up a quarto document, load the dataset, and inspect it (10 min)
    2. Create a data table with the total number of referrals received and accepted per month (10 min)
    3. Plot referrals per month (15 min)
        (hint: you will need to convert the `Month` column to a date; you can ask ChatGPT)
- Break
- [Assessment 2](https://psyteachr.github.io/reprores-v4/assessment-2.html) questions


## Class 05 (2024-10-25)

### Pre-Class

- Read [Chapter 5: Data Relations](https://psyteachr.github.io/reprores-v4/05-join.html)
- Look at the [exercises](https://psyteachr.github.io/reprores-v4/05-join.html#exercises)

### In-Class

- Open the [class book](https://psyteachr.github.io/reprores-v4/)
- Open RStudio 
- Start at 13:05
- Paired programming of [Chapter 5 exercises](https://psyteachr.github.io/reprores-v4/05-join.html#exercises)
    1. [Grade data](https://psyteachr.github.io/reprores-v4/05-join.html#grade-data): Set up a quarto document, load the datasets, and inspect them (10 min)
    2. [Matching the variable types](https://psyteachr.github.io/reprores-v4/05-join.html#matching-the-variable-types) and [Complete records](https://psyteachr.github.io/reprores-v4/05-join.html#complete-records) (10 min)
- Lisa will probably gibber about joins a lot!
- Break
- Paired programming:
    3. [Missing data](https://psyteachr.github.io/reprores-v4/05-join.html#missing-data) (20 min)
- More joins questions
- Assessment 3 introduction
