---
title: "Plot Report"
format: html
execute: 
  echo: false
  warning: false
---

```{r}
#| label: setup
#| include: false

library(tidyverse) 
library(patchwork) 
library(ggthemes)  

theme_set(theme_solarized(base_size = 18))

personality <- read_csv("https://psyteachr.github.io/reprores/data/personality_scores.csv")
```

## Overview

* ID: unique ID
* Ag : Agreeableness score


## Agreeableness Distribution

```{r}
ggplot(personality, aes(x = Ag)) +
  geom_histogram(binwidth = 0.25, 
                 colour = "black",
                 fill = "firebrick")
```

## All Distributions

```{r}
ag <- ggplot(personality, aes(x = Ag)) +
  geom_histogram(
    binwidth = 0.25,
    boundary = 0,
    colour = "black",
    fill = "firebrick"
  )

co <- ggplot(personality, aes(x = Co)) +
  geom_histogram(
    binwidth = 0.25,
    boundary = 0,
    colour = "black",
    fill = "darkorange"
  )

ne <- ggplot(personality, aes(x = Ne)) +
  geom_histogram(binwidth = 0.25,
                 boundary = 0,
                 colour = "black",
                 fill = "goldenrod2")

op <- ggplot(personality, aes(x = Op)) +
  geom_histogram(binwidth = 0.25,
                 boundary = 0,
                 colour = "black",
                 fill = "darkgreen")

ex <- ggplot(personality, aes(x = Ex)) +
  geom_histogram(binwidth = 0.25,
                 boundary = 0,
                 colour = "black",
                 fill = "dodgerblue3")
```

```{r}
#| fig-asp: 3
ag + co + ne + op + ex+ plot_layout(nrow = 5)

ggsave("myplot2.png", width = 10, height = 30)
```


