---
title: ReproRes 2022
output: 
  html_document:
    toc: true
    toc_depth: 2
  md_document:
    toc: true
    toc_depth: 2
---

## Class 01 (2024-09-27)


### Pre-class 

- Make sure you can access [Moodle](https://moodle.gla.ac.uk/course/view.php?id=44432)
- Bookmark the [Teams channel for PSYCH5077](https://sway.cloud.microsoft/ZRGtRvWTGltD5q3P) and Introduce yourself
- Read the [overview](https://psyteachr.github.io/reprores-v4/) and [Chapter 1](https://psyteachr.github.io/reprores-v4/01-intro.html) of the textbook
- Install R and RStudio on your computer
    - post on Teams if you run into problems
    - if you don't have a personal computer, you can use university computers; log on and familiarise yourself with R and RStudio
    - If you have a chromebook or tablet, you can't install R, but can use the RStudio server (log in with your GUID)
- Download and render the [test file](https://debruine.github.io/reprores_2024/reprores_test.qmd){download} to check that your setup is accurate
- Add these assessment dates to your diary
    - 2024-10-09 (10%) A project with a qmd file showing basic reproducible report skills (chapters 1-2)
    - 2024-10-23 (20%) A project demonstrating data visualisation and summary skills (chapters 3-4)
    - 2024-11-13 (30%) A project demonstrating data wrangling skills (chapters 5-7)
    - 2024-12-11 (40%) A project showing power simulation (chapters 8-10)
- Fill out the [pre-class poll](https://forms.gle/iPwNuTg5aooVjSvN7)

### In-Class

- [Poll 1](https://debruine.github.io/reprores_2024/polls/poll-01.html)
- Open the [class book](https://psyteachr.github.io/reprores-v4/)
- Open RStudio 
- Start at 13:05
- [Why Code?](https://debruine.github.io/why-code/) presentation
- Discuss the [class syllabus](https://moodle.gla.ac.uk/course/view.php?id=44432)
- Break
- [Chapter 1](https://psyteachr.github.io/reprores-v4/01-intro.html) live code

### Class Notes

- log into desktops with campus\12345678X and GUID password


### After Class

- Read [Chapter 2: Reports](https://psyteachr.github.io/reprores-v4/02-reports.html)
- Complete the [exercises](https://psyteachr.github.io/reprores-v4/02-reports.html#sec-exercises-reports) for chapter 2
- Look at [assessment 1](https://psyteachr.github.io/reprores-v4/assessment-1.html)
